@SuperAppBackend.WebApi_HostAddress = https://localhost:7152
@accessToken = put-token-here

GET {{SuperAppBackend.WebApi_HostAddress}}/api/health
Accept: application/json

###

POST {{SuperAppBackend.WebApi_HostAddress}}/api/auth/development
Content-Type: application/json

{
  "email": "demo@superapp.local",
  "fullName": "Demo User",
  "deviceName": "Local Swagger",
  "preferredCurrency": "KZT"
}

###

POST {{SuperAppBackend.WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@superapp.local",
  "password": "Admin123!",
  "deviceName": "Local Swagger"
}

###

GET {{SuperAppBackend.WebApi_HostAddress}}/api/accounts
Accept: application/json
Authorization: Bearer {{accessToken}}

###
