name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.220.53.240
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/superapp-src || git clone https://github.com/baiaman1/SuperApp.git /var/www/superapp-src
            cd /var/www/superapp-src
            git pull
            dotnet publish -c Release -o /var/www/superapp
            sudo systemctl restart superapp
